// <auto-generated />
namespace OnlineExam.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addall1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addall1));
        
        string IMigrationMetadata.Id
        {
            get { return "202003071124543_addall1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
